namespace:
  name: sandbox

service:
  port: 3111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP
 
image:
  repository: abdullahmeda/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz